apiVersion: v1
kind: Pod
metadata:
  name: no-api-demo
  namespace: day17-rbac
spec:
  serviceAccountName: inference-reader
  automountServiceAccountToken: false

  containers:
    - name: nginx
      image: nginx
