#!/usr/bin/env python3
from pathlib import Path
import argparse

BASE = Path.cwd()

READMES = {}

READMES['day1-linux'] = '# Day 1 — Linux Fundamentals\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Build comfort with the Linux shell and filesystem.\n- Understand processes, permissions, environment variables, and common command-line workflows.\n- Develop the foundation needed for container, Kubernetes, and server troubleshooting.\n\n## Core topics\n- Shell navigation and file operations\n- Processes and process inspection\n- Permissions and ownership\n- Environment variables\n- Pipes, redirection, and command composition\n\n## Commands to retain\n```bash\npwd\nls -lah\ncd\ncp\nmv\nrm\ncat\nless\ngrep\nfind\nps\ntop\nchmod\nchown\nenv\n```\n\n## AI-infrastructure relevance\nMost AI infrastructure ultimately runs on Linux. Being able to inspect files, processes, permissions, and runtime state quickly is foundational for debugging model servers, containers, GPU nodes, and cluster workloads.\n\n## Interview takeaway\nWhen diagnosing a Linux host, first establish the current system state before changing anything: inspect processes, resources, files, permissions, and logs, then narrow the problem to the appropriate layer.\n'

READMES['day2-gpu-benchmarking'] = '# Day 2 — GPU Benchmarking, PyTorch CUDA & VRAM\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Verify that PyTorch can access the GPU.\n- Understand synchronization when measuring GPU execution time.\n- Inspect GPU utilization and VRAM consumption.\n- Build intuition for CPU/GPU execution differences.\n\n## Core topics\n- CUDA availability in PyTorch\n- Moving tensors/models between CPU and GPU\n- GPU synchronization\n- GPU utilization\n- VRAM allocation\n- Benchmarking methodology\n\n## Commands / checks to retain\n```bash\nnvidia-smi\n```\n\n```python\nimport torch\nprint(torch.cuda.is_available())\nprint(torch.cuda.get_device_name(0))\n```\n\nFor reliable GPU timing, synchronize around the region being measured:\n\n```python\ntorch.cuda.synchronize()\n# start timing\n# GPU work\ntorch.cuda.synchronize()\n# stop timing\n```\n\n## AI-infrastructure relevance\nGPU infrastructure work requires distinguishing model/application bottlenecks from GPU availability, memory, utilization, and synchronization effects.\n\n## Interview takeaway\nGPU work is asynchronous. Timing GPU code without synchronization can produce misleading measurements, and utilization alone does not explain whether a workload is compute-, memory-, or input-bound.\n'

READMES['day3-processes'] = '# Day 3 — Processes, Signals & Job Control\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Understand how Linux creates, tracks, and terminates processes.\n- Use signals and job-control tools safely.\n- Recognize zombie and orphan process behavior.\n\n## Core topics\n- PIDs and parent/child relationships\n- Foreground and background jobs\n- Signals\n- `nice` / priority\n- `nohup`\n- Zombie processes\n\n## Commands to retain\n```bash\nps aux\nps -ef\npgrep\nkill\nkill -TERM <pid>\nkill -KILL <pid>\njobs\nbg\nfg\nnohup <command> &\nnice\nrenice\n```\n\n## AI-infrastructure relevance\nLong-running training and inference jobs are ordinary operating-system processes underneath higher-level orchestration. Process-level reasoning remains useful even when Kubernetes or Slurm is involved.\n\n## Interview takeaway\nPrefer graceful termination (`SIGTERM`) before forced termination (`SIGKILL`), and distinguish a process that is consuming resources from a zombie, which has exited but still has an unreaped process-table entry.\n'

READMES['day4-systemd'] = '# Day 4 — systemd, Services & Resource Controls\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Understand how Linux services are started and supervised.\n- Inspect service failures and restart behavior.\n- Connect service management to cgroups and resource isolation.\n\n## Core topics\n- `systemd` units\n- Service status and logs\n- Restart policies\n- cgroups\n- CPU and memory controls\n\n## Commands to retain\n```bash\nsystemctl status <service>\nsystemctl start <service>\nsystemctl stop <service>\nsystemctl restart <service>\nsystemctl enable <service>\njournalctl -u <service>\njournalctl -u <service> -f\n```\n\n## AI-infrastructure relevance\nGPU agents, container runtimes, node services, exporters, and model-serving components commonly run as managed system services.\n\n## Interview takeaway\nA service being configured correctly does not guarantee it is healthy. Inspect both service state and its logs, and understand whether repeated restarts are a symptom rather than the root cause.\n'

READMES['day5-networking'] = "# Day 5 — Linux Networking Fundamentals\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Understand interfaces, IP addressing, routes, DNS, sockets, ports, and CIDR.\n- Trace the path between an application and a remote service.\n- Diagnose common connectivity failures.\n\n## Core topics\n- Network interfaces\n- IP addresses and routing\n- TCP/UDP ports\n- DNS resolution\n- Listening sockets\n- CIDR notation\n\n## Commands to retain\n```bash\nip addr\nip route\nss -tulpn\nping\ncurl\nwget\nnslookup\ndig\n```\n\n## AI-infrastructure relevance\nDistributed training, Kubernetes Services, model APIs, storage systems, and GPU clusters all depend on reliable networking.\n\n## Interview takeaway\nSeparate name-resolution problems, routing problems, port/listener problems, and application-level failures rather than treating every connectivity issue as simply 'the network.'\n"

READMES['day6-storage-io'] = '# Day 6 — Storage & I/O Fundamentals\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Understand filesystems, mounts, inodes, and disk usage.\n- Identify storage and I/O bottlenecks.\n- Connect Linux storage concepts to container and Kubernetes storage.\n\n## Core topics\n- Filesystems and mount points\n- Block devices\n- Disk usage\n- Inodes\n- I/O utilization and bottlenecks\n\n## Commands to retain\n```bash\ndf -h\ndf -i\ndu -sh\nlsblk\nmount\nfindmnt\niostat\n```\n\n## AI-infrastructure relevance\nModel checkpoints, datasets, container layers, logs, and training pipelines can all become storage bottlenecks. Capacity and I/O performance are separate concerns.\n\n## Interview takeaway\nA filesystem can fail because it is out of bytes, out of inodes, unavailable, mounted incorrectly, or too slow. Diagnose which dimension is actually constrained.\n'

READMES['day7-docker'] = '# Day 7 — Docker Fundamentals\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Understand images, containers, ports, networks, volumes, and container lifecycle.\n- Package a reproducible application environment.\n- Connect containers to later Kubernetes concepts.\n\n## Core topics\n- Images vs containers\n- Dockerfiles\n- Port publishing\n- Volumes\n- Container networking\n- GPU-enabled containers\n- Container lifecycle\n\n## Commands to retain\n```bash\ndocker build\ndocker run\ndocker ps\ndocker logs\ndocker exec\ndocker inspect\ndocker images\ndocker stop\ndocker rm\ndocker volume ls\ndocker network ls\n```\n\n## AI-infrastructure relevance\nProduction inference and training workloads are commonly distributed as container images. Container literacy is therefore a prerequisite for Kubernetes-based AI infrastructure.\n\n## Interview takeaway\nAn image is the immutable package/template; a container is a running instance of that image with runtime state, networking, and optional persistent mounts.\n'

READMES['day8-compose'] = '# Day 8 — Docker Compose\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Run multiple dependent services as one application stack.\n- Configure service-to-service networking, volumes, environment variables, and health checks.\n- Understand dependency and readiness behavior in multi-service systems.\n\n## Core topics\n- Compose services\n- Networks\n- Volumes\n- Environment configuration\n- Health checks\n- Multi-container application lifecycle\n\n## Example architecture\n```text\nApplication\n    |\n    +--> API / worker\n    |\n    +--> PostgreSQL\n```\n\n## Commands to retain\n```bash\ndocker compose up\ndocker compose up -d\ndocker compose ps\ndocker compose logs\ndocker compose down\n```\n\n## AI-infrastructure relevance\nCompose is a useful bridge between single-container development and orchestration systems such as Kubernetes.\n\n## Interview takeaway\nA container being started does not necessarily mean its application is ready. Health checks and dependency behavior matter in multi-service systems.\n'

READMES['day9-kubernetes'] = '# Day 9 — Kubernetes Fundamentals\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Understand Pods, ReplicaSets, Deployments, the scheduler, and kubelet.\n- Learn how Kubernetes continuously reconciles desired and actual state.\n- Distinguish bare Pods from controller-managed workloads.\n\n## Core topics\n- Pods\n- ReplicaSets\n- Deployments\n- Scheduler\n- kubelet\n- Labels and selectors\n- Declarative desired state\n\n## Key lessons\n- A ReplicaSet maintains the requested number of Pods.\n- A Deployment manages ReplicaSets and enables controlled rollouts.\n- The scheduler chooses a node; the kubelet runs the assigned Pod.\n- Bare Pods are not automatically recreated by a higher-level controller.\n\n## Commands to retain\n```bash\nkubectl get pods\nkubectl get deployments\nkubectl get replicasets\nkubectl describe pod <pod>\nkubectl apply -f <manifest>\nkubectl delete -f <manifest>\n```\n\n## Interview takeaway\nKubernetes is a reconciliation system: controllers continually compare desired state with actual state and act to reduce the difference.\n'

READMES['day10-kubernetes-networking'] = '# Day 10 — Kubernetes Networking\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Understand how Services provide stable access to changing Pods.\n- Use labels, selectors, EndpointSlices, DNS, and Ingress to trace traffic.\n- Diagnose Service-to-Pod connectivity problems.\n\n## Core topics\n- Pod IPs\n- Services\n- ClusterIP\n- EndpointSlices\n- Kubernetes DNS\n- Ingress\n- NetworkPolicy basics\n\n## Diagnostic path\n```text\nClient\n  ↓\nIngress\n  ↓\nService\n  ↓\nEndpointSlice\n  ↓\nPod\n```\n\n## Commands to retain\n```bash\nkubectl get svc\nkubectl describe svc <service>\nkubectl get endpointslices\nkubectl get pods --show-labels\nkubectl get ingress\n```\n\n## Key lesson\nA Service selector must match Pod labels. Healthy Pods do not help if the Service has no matching endpoints.\n\n## Interview takeaway\nWhen a Service exists but traffic fails, verify selectors, EndpointSlices, target ports, DNS, and the application listener before restarting Pods.\n'

READMES['day11-kubernetes-storage'] = '# Day 11 — Kubernetes Storage\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Understand ephemeral and persistent storage in Kubernetes.\n- Distinguish PVs, PVCs, StorageClasses, and StatefulSets.\n- Reason about storage lifecycle independently from Pod lifecycle.\n\n## Core topics\n- `emptyDir`\n- PersistentVolumes (PV)\n- PersistentVolumeClaims (PVC)\n- StorageClasses\n- Access modes\n- StatefulSets\n\n## Key lessons\n- A PVC expresses a storage request; a PV represents provisioned storage.\n- Deleting a Pod does not necessarily delete its persistent data.\n- StatefulSets provide stable identities and predictable storage relationships.\n\n## Commands to retain\n```bash\nkubectl get pv\nkubectl get pvc\nkubectl describe pvc <pvc>\nkubectl get statefulset\nkubectl describe pod <pod>\n```\n\n## Interview takeaway\nSeparate Pod lifecycle from storage lifecycle. A recreated Pod can often reconnect to persistent storage if the PVC and backing volume still exist.\n'

READMES['day12-kubernetes-config'] = '# Day 12 — ConfigMaps, Secrets & Configuration Rollouts\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Manage application configuration separately from container images.\n- Understand ConfigMaps, Secrets, environment injection, and mounted configuration.\n- Recognize when configuration changes do and do not reach running Pods.\n\n## Core topics\n- ConfigMaps\n- Secrets\n- `envFrom`\n- `configMapKeyRef`\n- `secretKeyRef`\n- Volume-mounted configuration\n- Rollout restarts\n\n## Key lessons\n- Environment variables are captured when the container starts.\n- Updating a ConfigMap does not automatically update environment variables in existing containers.\n- Mounted configuration can behave differently depending on how the application reads it.\n- Missing required keys can prevent container creation.\n\n## Commands to retain\n```bash\nkubectl get configmap\nkubectl get secret\nkubectl describe pod <pod>\nkubectl rollout restart deployment <deployment>\nkubectl rollout status deployment <deployment>\n```\n\n## Interview takeaway\nAlways determine how configuration enters the container before assuming that changing the Kubernetes object changes the running application.\n'

READMES['day13-k8s-scheduling'] = '# Day 13 — Kubernetes Scheduling & Resource Management\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Understand requests, limits, node selection, affinity, taints, and tolerations.\n- Diagnose why Pods remain Pending.\n- Reason about placement constraints for CPU, memory, and accelerator workloads.\n\n## Core topics\n- CPU and memory requests\n- Resource limits\n- `nodeSelector`\n- Node affinity\n- Taints and tolerations\n- Scheduler decisions\n\n## Key lessons\n- Requests influence scheduling.\n- Limits constrain runtime resource usage.\n- A toleration permits scheduling onto a tainted node but does not force placement there.\n- Required affinity is a hard constraint; preferred affinity is a preference.\n\n## Commands to retain\n```bash\nkubectl describe pod <pod>\nkubectl describe node <node>\nkubectl get nodes --show-labels\nkubectl taint nodes <node> key=value:NoSchedule\n```\n\n## Interview takeaway\nFor a Pending Pod, inspect scheduler events first. CPU/memory shortages, affinity, selectors, and untolerated taints are scheduling-layer failures, not application failures.\n'

READMES['day14-probes'] = '# Day 14 — Kubernetes Health Probes\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Distinguish liveness, readiness, and startup probes.\n- Understand how probe failures affect traffic and container lifecycle.\n- Avoid probes that create unnecessary restarts.\n\n## Core topics\n- Liveness probes\n- Readiness probes\n- Startup probes\n- HTTP, TCP, and exec probes\n\n## Mental model\n```text\nstartup  → Can the application finish starting?\nreadiness → Should this Pod receive traffic?\nliveness → Is the running container unhealthy enough to restart?\n```\n\n## Key lessons\n- Readiness failure removes a Pod from normal Service traffic without necessarily restarting it.\n- Liveness failure can restart the container.\n- Startup probes protect slow-starting applications from premature liveness/readiness evaluation.\n\n## Interview takeaway\nChoose probes based on the failure response you actually want. External dependency failure is often a poor liveness signal because restarting the application may not fix the dependency.\n'

READMES['day15-autoscaling'] = '# Day 15 — Kubernetes Autoscaling\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Understand HPA, VPA, and cluster autoscaling.\n- Relate observed utilization to replica recommendations.\n- Reason about stabilization, cooldown behavior, and queue-based scaling.\n\n## Core topics\n- Horizontal Pod Autoscaler (HPA)\n- Vertical Pod Autoscaler (VPA)\n- Cluster Autoscaler\n- CPU utilization targets\n- Stabilization and thrashing\n- Queue-based scaling\n- GPU-aware scaling considerations\n\n## Mental model\n```text\nHPA             → more/fewer Pods\nVPA             → more/fewer resources per Pod\nCluster Autoscaler → more/fewer nodes\n```\n\n## Key lesson\nHigh GPU utilization is not automatically bad if latency and service objectives are still being met. Scaling decisions should use workload and quality-of-service signals.\n\n## Interview takeaway\nAutoscaling should respond to the bottleneck that represents demand: CPU may work for some workloads, while queue depth, latency, request rate, or GPU metrics may be better for AI services.\n'

READMES['day16-helm'] = '# Day 16 — Helm Fundamentals\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Package and parameterize Kubernetes applications.\n- Understand charts, values, templates, releases, upgrades, and rollbacks.\n- Reduce duplicated manifests across environments.\n\n## Core topics\n- Helm charts\n- `values.yaml`\n- Templates\n- Releases\n- Upgrade\n- Rollback\n- `upgrade --install`\n\n## Key lessons\n- A chart is a package of Kubernetes templates and defaults.\n- A release is an installed instance of a chart.\n- Rollback creates another release revision; revision numbers continue increasing.\n- Runtime controllers such as HPA can change replica counts independently of Helm values.\n\n## Commands to retain\n```bash\nhelm install\nhelm upgrade\nhelm upgrade --install\nhelm list\nhelm history\nhelm rollback\nhelm get values\n```\n\n## Interview takeaway\nHelm manages desired deployment configuration, but Kubernetes controllers can still modify live state. Always distinguish chart values from current cluster state.\n'

READMES['day17-rbac'] = '# Day 17 — Kubernetes RBAC, ServiceAccounts & Basic Security\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Understand how Kubernetes identities receive permissions.\n- Distinguish ServiceAccounts, Roles, ClusterRoles, and bindings.\n- Apply least-privilege thinking to workloads.\n\n## Core topics\n- ServiceAccounts\n- Roles\n- ClusterRoles\n- RoleBindings\n- ClusterRoleBindings\n- Authorization checks\n- Least privilege\n\n## Mental model\n```text\nIdentity\n   ↓\nServiceAccount / user\n   ↓\nBinding\n   ↓\nRole / ClusterRole\n   ↓\nAllowed API actions\n```\n\n## Commands to retain\n```bash\nkubectl get serviceaccounts\nkubectl get roles\nkubectl get rolebindings\nkubectl auth can-i <verb> <resource>\nkubectl auth can-i --as=system:serviceaccount:<namespace>:<sa> <verb> <resource>\n```\n\n## Interview takeaway\nAuthentication identifies the caller; authorization determines what that identity may do. Prefer narrowly scoped permissions instead of broad cluster-wide access.\n'

READMES['day18-workloads'] = '# Day 18 — Jobs, CronJobs, Init Containers & Workload Lifecycle\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Distinguish long-running services from finite/batch workloads.\n- Use Jobs and CronJobs for completion-oriented work.\n- Understand init containers and workload lifecycle sequencing.\n\n## Core topics\n- Jobs\n- CronJobs\n- Restart/completion behavior\n- Init containers\n- Pod lifecycle\n- Batch workload patterns\n\n## Mental model\n```text\nDeployment → keep service running\nJob        → run until successful completion\nCronJob    → create Jobs on a schedule\nInit container → finish setup before app containers start\n```\n\n## Commands to retain\n```bash\nkubectl get jobs\nkubectl get cronjobs\nkubectl describe job <job>\nkubectl logs job/<job>\nkubectl create job\n```\n\n## Interview takeaway\nChoose the controller that matches workload semantics. A batch task should normally model completion rather than being forced into a long-running Deployment pattern.\n'

READMES['day19-observability'] = '# Day 19 — Kubernetes Observability, Debugging & Failure Diagnosis\n\n**Roadmap:** AI Infrastructure & ML Systems  \n**Status:** Completed\n\n## Objectives\n- Develop a systematic Kubernetes troubleshooting workflow.\n- Use state, events, logs, metrics, and in-container inspection as evidence.\n- Distinguish visible symptoms from underlying causes.\n\n## Default diagnostic funnel\n```text\nGET → DESCRIBE → LOGS → METRICS → EXEC\n```\n\n## Failure classes practiced\n\n### ImagePullBackOff\nAn invalid image tag produced `ErrImagePull`, followed by retry/backoff behavior and `ImagePullBackOff`.\n\n### CrashLoopBackOff\nThe container started successfully, but the application process exited repeatedly because required configuration was missing.\n\n### Running but NotReady\nThe application was alive, but a readiness probe checked a nonexistent `/healthz` endpoint and received HTTP 404.\n\n### Service / EndpointSlice failure\nHealthy Pods used `app=model-api`, while the Service selected `app=inference-api`, leaving the Service with no usable endpoints.\n\n### FailedScheduling\nA Pod requested 20 CPUs on a Minikube node with only 16 allocatable CPUs and remained `Pending` with `PodScheduled=False`.\n\n## Commands to retain\n```bash\nkubectl get pods\nkubectl get pods -o wide\nkubectl describe pod <pod>\nkubectl logs <pod>\nkubectl logs <pod> --previous\nkubectl top pod <pod>\nkubectl top nodes\nkubectl get endpointslices\nkubectl describe svc <service>\nkubectl exec -it <pod> -- /bin/sh\nkubectl get events --sort-by=.metadata.creationTimestamp\n```\n\n## Failure-state mental model\n```text\nPending              → scheduling/resources\nContainerCreating    → node/runtime/storage/network preparation\nImagePullBackOff     → image/registry\nCrashLoopBackOff     → process starts then fails\nOOMKilled            → memory termination\nRunning 0/1          → readiness\nHealthy Pods + no Service traffic → selector/EndpointSlice/port path\n```\n\n## Interview takeaway\nObserve before changing anything. Correlate Kubernetes state and events with application logs, metrics, Service/EndpointSlice information, and node conditions; identify the failing layer and separate the symptom from the root cause before applying a fix.\n'

parser = argparse.ArgumentParser(
    description="Create Day 1–19 README.md files for the AI infrastructure study repo."
)
parser.add_argument(
    "--force",
    action="store_true",
    help="Overwrite README.md files that already exist."
)
args = parser.parse_args()

created = []
skipped = []

for folder, content in READMES.items():
    d = BASE / folder
    d.mkdir(parents=True, exist_ok=True)
    readme = d / "README.md"

    if readme.exists() and not args.force:
        skipped.append(str(readme))
        continue

    readme.write_text(content, encoding="utf-8")
    created.append(str(readme))

print("Created/updated:")
for p in created:
    print(f"  {p}")

if skipped:
    print("\nSkipped existing READMEs (use --force to overwrite):")
    for p in skipped:
        print(f"  {p}")
