apiVersion: v1
kind: Pod
metadata:
  name: real-gpu-pod
spec:
  nodeSelector:
    accelerator: gpu

  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"

  containers:
    - name: gpu-test
      image: nvidia/cuda:12.4.1-base-ubuntu22.04
      command: ["bash", "-c", "nvidia-smi && sleep 3600"]

      resources:
        limits:
          nvidia.com/gpu: 1
