apiVersion: v1
kind: Pod
metadata:
  name: gpu-contender
  namespace: day27
spec:
  restartPolicy: Never
  containers:
    - name: worker
      image: ubuntu:24.04
      command: ["/bin/sh", "-c"]
      args: ["sleep 1800"]
      resources:
        limits:
          nvidia.com/gpu: 1
