apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-demo
spec:
  replicas: 1

  selector:
    matchLabels:
      app: readiness-demo

  template:
    metadata:
      labels:
        app: readiness-demo

    spec:
      containers:
        - name: nginx
          image: nginx:alpine

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /ready
              port: 80

            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
            successThreshold: 1
