apiVersion: v1
kind: Pod
metadata:
  name: affinity-required
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: accelerator
                operator: In
                values:
                  - gpu
                  - tpu

  containers:
    - name: web
      image: nginx:alpine
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
