apiVersion: v1
kind: Pod
metadata:
  name: gpu-placement-demo
spec:
  nodeSelector:
    accelerator: gpu

  containers:
    - name: web
      image: nginx:alpine
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
