apiVersion: v1
kind: Pod
metadata:
  name: impossible-pod
spec:
  containers:
    - name: worker
      image: nginx:alpine
      resources:
        requests:
            cpu: "500m"
            memory: "128Mi"
        limits:
            cpu: "2"
            memory: "256Mi"
