apiVersion: v1
kind: Pod
metadata:
  name: emptydir-restart-demo
spec:
  containers:
    - name: demo
      image: busybox
      command:
        - sh
        - -c
        - |
          touch /tmp/healthy
          sleep 3600

      volumeMounts:
        - name: data
          mountPath: /data

      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 1

  volumes:
    - name: data
      emptyDir: {}
