apiVersion: v1
kind: Pod
metadata:
  name: model-writer
spec:
  containers:
    - name: writer
      image: busybox
      command: ["sh", "-c", "sleep 3600"]

      volumeMounts:
        - name: model-volume
          mountPath: /models

  volumes:
    - name: model-volume
      persistentVolumeClaim:
        claimName: model-storage
